Stolarus2/Controllers/HomeController.cs
using Stolarus2.Data.Contracts;
using Stolarus2.Data.Models;
using Stolarus2.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace Stolarus2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string lang)
        {
            SinglePage model = new SinglePage();

            ISlidersRepository slidersRepository = DependencyResolver.Current.GetService<ISlidersRepository>();
            model.Sliders = slidersRepository.GetList().ToList();

            IArticleRepository articleRepository = DependencyResolver.Current.GetService<IArticleRepository>();
            model.About = articleRepository.GetList().Where(x => x.ArticleCategory == ArticleCategory.About).ToList();

            IProductCategoriesRepository productCategoryRepository = DependencyResolver.Current.GetService<IProductCategoriesRepository>();
            model.ProductCategories = productCategoryRepository.GetList().Take(3).ToList();

            IPortfoliosRepository portfolioRepository = DependencyResolver.Current.GetService<IPortfoliosRepository>();
            model.Portfolios = portfolioRepository.GetList().Take(5).ToList();

            IContactsRepository contactRepository = DependencyResolver.Current.GetService<IContactsRepository>();
            model.Contacts = contactRepository.GetList().ToList();

            return View(model);
        }
    }
}

Stolarus2/Controllers/ProductCategoriesController.cs
using System.Linq;
using System.Web.Mvc;
using Stolarus2.Data.Contracts;
using Stolarus2.ViewModels;

namespace Stolarus2.Controllers
{
    public class ProductCategoriesController : Controller
    {
        public ActionResult Index()
        {
            ProductCategoriesInfo model = new ProductCategoriesInfo();

            IProductCategoriesRepository productCategoryRepository = DependencyResolver.Current.GetService<IProductCategoriesRepository>();
            model.ProductCategories = productCategoryRepository.GetList().ToList();

            return View(model);
        }
    }
}

Stolarus2/Controllers/ProductsController.cs
using System.Linq;
using System.Web.Mvc;
using Stolarus2.Data.Contracts;
using Stolarus2.Data.Models;
using Stolarus2.ViewModels;

namespace Stolarus2.Controllers
{
    public class ProductsController : Controller
    {
        public ActionResult Index(int id)
        {
            ProductsInfo model = new ProductsInfo();

            IProductCategoriesRepository productCategoryRepository = DependencyResolver.Current.GetService<IProductCategoriesRepository>();

            ProductCategory productCategory = productCategoryRepository.GetById(id);

            model.CategoryName = productCategory.Name;
            model.CategoryDescription = productCategory.Description;
            model.Products = productCategory.Products.ToList();

            return View(model);
        }
    }
}

Stolarus2/Views/Home/Index.cshtml
@using Stolarus2.Data.Models
@using Stolarus2.Helpers

@model Stolarus2.ViewModels.SinglePage

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--========== SLIDER ==========-->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <div class="container">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            @{
                int index = 0;
            }
            @foreach (Slider slider in Model.Sliders)
            {
                <li data-target="#@index" data-slide-to="@index" class="@(index == 0 ? "active" : "")"></li>
                index++;
            }
        </ol>
    </div>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        @{
            index = 0;
        }
        @foreach (Slider slider in Model.Sliders)
        {
            <div class="@(index == 0 ? "item active" : "item")">
                <img class="img-responsive" src="@slider.ImageID.GetPath(1920, 1080)" alt="@slider.Name">
                <div class="container">
                    <div class="carousel-centered">
                        <div class="margin-b-40">
                            <h1 class="carousel-title">@slider.Name</h1>
                        </div>
                        <a href="@slider.ExternalURL" class="btn-theme btn-theme-sm btn-white-brd text-uppercase">Explore</a>
                    </div>
                </div>
            </div>

            index++;
        }
    </div>
</div>
<!--========== SLIDER ==========-->
<!--========== PAGE LAYOUT ==========-->
<!-- About -->
<div id="about">
    <div class="content-lg container">
        <!-- Masonry Grid -->
        <div class="masonry-grid row">
            <div class="masonry-grid-sizer col-xs-6 col-sm-6 col-md-1"></div>

            @if (@Model.About.Count > 0)
            {
                <div class="masonry-grid-item col-xs-12 col-sm-6 col-md-4 sm-margin-b-30">
                    <div class="margin-b-60">
                        <h2>@Model.About[0].Name</h2>
                        <p>@Model.About[0].Description</p>
                    </div>
                    <img class="full-width img-responsive wow fadeInUp" src="@Model.About[0].ImageID.GetPath(500, 500)" alt="@Model.About[0].Name" data-wow-duration=".3" data-wow-delay=".2s">
                </div>
            }

            @if (@Model.About.Count > 1)
            {
                <div class="masonry-grid-item col-xs-12 col-sm-6 col-md-4">
                    <div class="margin-b-60">
                        <img class="full-width img-responsive wow fadeInUp" src="@Model.About[1].ImageID.GetPath(500, 500)" alt="@Model.About[1].Name" data-wow-duration=".3" data-wow-delay=".3s">
                    </div>
                    <h2>@Model.About[1].Name</h2>
                    <p>@Model.About[1].Description</p>
                </div>
            }

            @if (@Model.About.Count > 2)
            {
                <div class="masonry-grid-item col-xs-12 col-sm-6 col-md-4">
                    <div class="margin-t-60 margin-b-60">
                        <h2>@Model.About[2].Name</h2>
                        <p>@Model.About[2].Description</p>
                    </div>
                    <img class="full-width img-responsive wow fadeInUp" src="@Model.About[2].ImageID.GetPath(500, 500)" alt="@Model.About[2].Name" data-wow-duration=".3" data-wow-delay=".4s">
                </div>
            }

        </div>
        <!-- End Masonry Grid -->
    </div>
</div>
<!-- End About -->
<!-- Latest Products -->
<div id="products">
    <div class="content-lg container">

        <div class="row margin-b-40">
            <div class="col-sm-6">
                <h2>Latest Products</h2>
            </div>
            <div class="col-sm-6">
                @Html.ActionLink("All Categories", "Index", "ProductCategories");
            </div>
        </div>
        <!--// end row -->

        <div class="row">

            @foreach (ProductCategory cat in Model.ProductCategories)
            {
                <!-- Latest Products -->
                <div class="col-sm-4 sm-margin-b-50">
                    <div class="margin-b-20">
                        <img class="img-responsive" src="@cat.ImageID.GetPath(970, 647)" alt="@cat.Name">
                    </div>
                    <h4><a href="#">@cat.Name</a></h4>
                    <p>@cat.Description</p>
                    @Html.ActionLink("Read More", "Index", "Products", new { @class = "link" })

                </div>
                <!-- End Latest Products -->
            }

        </div>
        <!--// end row -->
    </div>
</div>
<!-- End Latest Products -->
<!-- Work -->
<div id="work">
    <div class="section-seperator">
        <div class="content-md container">
            <div class="row margin-b-40">
                <div class="col-sm-6">
                    <h2>Work</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed tempor incididunt ut laboret dolore magna aliqua enim minim veniam exercitation</p>
                </div>
            </div>
            <!--// end row -->
            <!-- Masonry Grid -->
            <div class="masonry-grid row">

                <div class="masonry-grid-sizer col-xs-6 col-sm-6 col-md-1"></div>

                @{
                    index = 0;
                }
                @foreach (Portfolio por in Model.Portfolios)
                {
                    if (index == 0)
                    {
                        <div class="masonry-grid-item col-xs-12 col-sm-6 col-md-8 margin-b-30">
                            <!-- Work -->
                            <div class="work work-popup-trigger">
                                <div class="work-overlay">
                                    <img class="full-width img-responsive" src="@por.ImageID.GetPath(800, 400)" alt="@por.Name">
                                </div>
                            </div>
                            <!-- End Work -->
                        </div>
                    }
                    else if (index == 1)
                    {
                        <div class="masonry-grid-item col-xs-12 col-sm-6 col-md-4 margin-b-30">
                            <!-- Work -->
                            <div class="work work-popup-trigger">
                                <div class="work-overlay">
                                    <img class="full-width img-responsive" src="@por.ImageID.GetPath(397, 415)" alt="@por.Name">
                                </div>
                            </div>
                            <!-- End Work -->
                        </div>
                    }
                    else
                    {
                        <div class="masonry-grid-item col-xs-12 col-sm-6 col-md-4 md-margin-b-30">
                            <!-- Work -->
                            <div class="work work-popup-trigger">
                                <div class="work-overlay">
                                    <img class="full-width img-responsive" src="@por.ImageID.GetPath(397, 300)" alt="@por.Name">
                                </div>
                            </div>
                            <!-- End Work -->
                        </div>
                    }
                    index++;
                }

            </div>
            <!-- End Masonry Grid -->
        </div>
    </div>
</div>
<!-- End Work -->
<!-- Contact -->
<div id="contact">
    <!-- Contact List -->
    <div class="section-seperator">
        <div class="content-lg container">
            <div class="row">

                @foreach (Contact cont in Model.Contacts)
                {
                    <div class="col-sm-4 sm-margin-b-50">
                        <h3><a href="/#">@cont.Name</a></h3>
                        <p>@cont.Description</p>
                        <ul class="list-unstyled contact-list">
                            <li><i class="margin-r-10 color-base icon-call-out"></i> 1 012 3456 7890</li>
                            <li><i class="margin-r-10 color-base icon-envelope"></i> hq@aitOnepage.com</li>
                        </ul>
                    </div>
                }

            </div>
            <!--// end row -->
        </div>
    </div>
    <!-- End Contact List -->
    <!-- Google Map -->
    <div id="map" class="map height-300"></div>
</div>
<!-- End Contact -->
<!--========== END PAGE LAYOUT ==========-->