Stolarus2.Admin/Controllers/ArticleController.cs
using System;
using System.Web.Mvc;
using Stolarus2.Data.Contracts;
using Stolarus2.Data.Models;

namespace Stolarus2.Admin.Controllers
{
    public class ArticleController : ApplicationController<Article, int>
    {
        private IArticleRepository repository;

        public ArticleController(IArticleRepository repository) : base(repository)
        {
            this.repository = repository;
        }

        public override ActionResult CreatePartial(Article entity)
        {
            entity.CreatedDateTime = DateTime.Now;
            return base.CreatePartial(entity);
        }
    }
}

Stolarus2.Admin/Controllers/ContactsController.cs
using System;
using System.Web.Mvc;
using Stolarus2.Data.Contracts;
using Stolarus2.Data.Models;

namespace Stolarus2.Admin.Controllers
{
    public class ContactsController : ApplicationController<Contact, int>
    {
        private IContactsRepository repository;

        public ContactsController(IContactsRepository repository) : base(repository)
        {
            this.repository = repository;
        }

        public override ActionResult CreatePartial(Contact entity)
        {
            entity.CreatedDateTime = DateTime.Now;
            return base.CreatePartial(entity);
        }
    }
}

Stolarus2.Admin/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Stolarus2.Admin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Stolarus2.Admin/Controllers/QuotesController.cs
using System;
using System.Web.Mvc;
using Stolarus2.Data.Contracts;
using Stolarus2.Data.Models;

namespace Stolarus2.Admin.Controllers
{
    public class QuotesController : ApplicationController<Quote, int>
    {
        private IQuotesRepository repository;

        public QuotesController(IQuotesRepository repository) : base(repository)
        {
            this.repository = repository;
        }

        public override ActionResult CreatePartial(Quote entity)
        {
            entity.CreatedDateTime = DateTime.Now;
            return base.CreatePartial(entity);
        }
    }
}

Stolarus2.Admin/Controllers/SlidersController.cs
using System;
using System.Web.Mvc;
using Stolarus2.Data.Contracts;
using Stolarus2.Data.Models;

namespace Stolarus2.Admin.Controllers
{
    public class SlidersController : ApplicationController<Slider, int>
    {
        private ISlidersRepository repository;

        public SlidersController(ISlidersRepository repository) : base(repository)
        {
            this.repository = repository;
        }

        public override ActionResult CreatePartial(Slider entity)
        {
            entity.CreatedDateTime = DateTime.Now;
            return base.CreatePartial(entity);
        }
    }
}

Stolarus2.Admin/Views/Home/Index.cshtml
@using Stolarus2.Data.Properties
@{
    ViewBag.Title = "Home Page";
}

<br /><br />

<ul>
    <li>@Html.ActionLink(Resources.Sliders, "Index", "Sliders")</li>
    <li>@Html.ActionLink(Resources.ProductCategories, "Index", "ProductCategories")</li>
    <li>@Html.ActionLink(Resources.Products, "Index", "Products")</li>
    <li>@Html.ActionLink(Resources.PortfolioTypes, "Index", "PortfolioTypes")</li>
    <li>@Html.ActionLink(Resources.Portfolios, "Index", "Portfolios")</li>
    <li>@Html.ActionLink(Resources.PortfolioDetails, "Index", "PortfolioDetails")</li>
    <li>@Html.ActionLink(Resources.Article, "Index", "Article")</li>
    <li>@Html.ActionLink(Resources.Quotes, "Index", "Quotes")</li>
    <li>@Html.ActionLink(Resources.Contacts, "Index", "Contacts")</li>
    <li>@Html.ActionLink(Resources.Certificates, "Index", "Certificates")</li>
</ul>